Fix clean parallel build
The newly introduced krfb-virtualmonitor also needs
ui_connectionwidget.h (via rfbclient -> connectiondialog) and fails
with "krfb/connectiondialog.h:25:10: fatal error: ui_connectionwidget.h:
No such file or directory #include "ui_connectionwidget.h" when doing
a clean build with a high enough number of jobs.
Fix it by introducing a krfb_UI_SRCS variable, which is used by both
executable targets.